import { NAME } from './constants';


export const SHIFTY_CONNECTING = `${NAME}/SHIFTY_CONNECTING`;
export const SHIFTY_CONNECTED = `${NAME}/SHIFTY_CONNECTED`;
export const SHIFTY_DISCONNECTED = `${NAME}/SHIFTY_DISCONNECTED`;
export const SHIFTY_ERROR = `${NAME}/SHIFTY_ERROR`;
export const SHIFTY_RECONNECT_ATTEMPT = `${NAME}/SHIFTY_RECONNECT_ATTEMPT`;
export const DUMPLING = `${NAME}/DUMPLING`;
