import { NAME } from './constants';


export const HUB_CONNECT = `${NAME}/HUB_CONNECT`;
export const HUB_DISCONNECT = `${NAME}/HUB_DISCONNECT`;

export const HUB_CONNECTING = `${NAME}/HUB_CONNECTING`;
export const HUB_UNAVAILABLE = `${NAME}/HUB_UNAVAILABLE`;
export const HUB_CONNECTED = `${NAME}/HUB_CONNECTED`;
export const HUB_DISCONNECTED = `${NAME}/HUB_DISCONNECTED`;
export const HUB_ERROR = `${NAME}/HUB_ERROR`;
export const HUB_RECONNECT_ATTEMPT = `${NAME}/HUB_RECONNECT_ATTEMPT`;
export const HUB_CANCEL_RECONNECT = `${NAME}/HUB_CANCEL_RECONNECT`;

export const DUMPLING = `${NAME}/DUMPLING`;
