import { NAME } from './constants';


export const SHIFTY_CONNECT = `${NAME}/SHIFTY_CONNECT`;
export const SHIFTY_DISCONNECT = `${NAME}/SHIFTY_DISCONNECT`;

export const SHIFTY_CONNECTING = `${NAME}/SHIFTY_CONNECTING`;
export const SHIFTY_UNAVAILABLE = `${NAME}/SHIFTY_UNAVAILABLE`;
export const SHIFTY_CONNECTED = `${NAME}/SHIFTY_CONNECTED`;
export const SHIFTY_DISCONNECTED = `${NAME}/SHIFTY_DISCONNECTED`;
export const SHIFTY_ERROR = `${NAME}/SHIFTY_ERROR`;
export const SHIFTY_RECONNECT_ATTEMPT = `${NAME}/SHIFTY_RECONNECT_ATTEMPT`;
export const SHIFTY_CANCEL_RECONNECT = `${NAME}/SHIFTY_CANCEL_RECONNECT`;

export const DUMPLING = `${NAME}/DUMPLING`;
